### ISSUE TITLE
Algorithm description

### ISSUE THREAD

**Issue by mavam** [rapidsai/distributed-join#23]
Hi there, I was wondering if there's a high-level description of the the distributed join algorithm available. Does it follow a text-book version or is it something custom?

**Comment by gaohao95** [comment]
Hi mavam,

This repo implements a repartitioned join algorithm. It basically follows three steps:
1. Hash partition: reorder input tables into buckets based on the hash values of the key columns
2. All-to-all communication: send buckets so that rows with the same hash values end up in the same MPI rank 
3. Local join: each MPI rank performs local join independently

@nsakharnykh and I gave a talk about the algorithm used and some optimizations in this year's GTC: https://developer.nvidia.com/gtc/2020/video/s21482

**Comment by mavam** [comment]
Thanks, this is exactly the level of information I needed!
